#pragma once
#include <raylib.h>
#include <map>
#include "Command.h"

static std::map<KeyboardKey, CommandType> s_keyboardKeyCommands = {
    {KEY_NULL,CommandType::NO_COMMAND},
    // Alphanumeric keys
    {KEY_APOSTROPHE,CommandType::NO_COMMAND},
    {KEY_COMMA,CommandType::NO_COMMAND},
    {KEY_MINUS,CommandType::NO_COMMAND},
    {KEY_PERIOD,CommandType::NO_COMMAND},
    {KEY_SLASH,CommandType::NO_COMMAND},
    {KEY_ZERO,CommandType::NO_COMMAND},
    {KEY_ONE,CommandType::NO_COMMAND},
    {KEY_TWO,CommandType::NO_COMMAND},
    {KEY_THREE,CommandType::NO_COMMAND},
    {KEY_FOUR,CommandType::NO_COMMAND},
    {KEY_FIVE,CommandType::NO_COMMAND},
    {KEY_SIX,CommandType::NO_COMMAND},
    {KEY_SEVEN,CommandType::NO_COMMAND},
    {KEY_EIGHT,CommandType::NO_COMMAND},
    {KEY_NINE,CommandType::NO_COMMAND},
    {KEY_SEMICOLON,CommandType::NO_COMMAND},
    {KEY_EQUAL,CommandType::NO_COMMAND},
    {KEY_A,CommandType::NO_COMMAND},
    {KEY_B,CommandType::NO_COMMAND},
    {KEY_C,CommandType::NO_COMMAND},
    {KEY_D,CommandType::NO_COMMAND},
    {KEY_E,CommandType::NO_COMMAND},
    {KEY_F,CommandType::NO_COMMAND},
    {KEY_G,CommandType::NO_COMMAND},
    {KEY_H,CommandType::NO_COMMAND},
    {KEY_I,CommandType::NO_COMMAND},
    {KEY_J,CommandType::NO_COMMAND},
    {KEY_K,CommandType::NO_COMMAND},
    {KEY_L,CommandType::NO_COMMAND},
    {KEY_M,CommandType::NO_COMMAND},
    {KEY_N,CommandType::NO_COMMAND},
    {KEY_O,CommandType::NO_COMMAND},
    {KEY_P,CommandType::NO_COMMAND},
    {KEY_Q,CommandType::NO_COMMAND},
    {KEY_R,CommandType::NO_COMMAND},
    {KEY_S,CommandType::NO_COMMAND},
    {KEY_T,CommandType::NO_COMMAND},
    {KEY_U,CommandType::NO_COMMAND},
    {KEY_V,CommandType::NO_COMMAND},
    {KEY_W,CommandType::NO_COMMAND},
    {KEY_X,CommandType::NO_COMMAND},
    {KEY_Y,CommandType::NO_COMMAND},
    {KEY_Z,CommandType::NO_COMMAND},
    {KEY_LEFT_BRACKET,CommandType::NO_COMMAND},
    {KEY_BACKSLASH,CommandType::NO_COMMAND},
    {KEY_RIGHT_BRACKET,CommandType::NO_COMMAND},
    {KEY_GRAVE,CommandType::NO_COMMAND},
    // Function keys
    {KEY_SPACE,CommandType::NO_COMMAND},
    {KEY_ESCAPE,CommandType::NO_COMMAND},
    {KEY_ENTER,CommandType::NO_COMMAND},
    {KEY_TAB,CommandType::NO_COMMAND},
    {KEY_BACKSPACE,CommandType::NO_COMMAND},
    {KEY_INSERT,CommandType::NO_COMMAND},
    {KEY_DELETE,CommandType::NO_COMMAND},
    {KEY_RIGHT,CommandType::NO_COMMAND},
    {KEY_LEFT,CommandType::NO_COMMAND},
    {KEY_DOWN,CommandType::NO_COMMAND},
    {KEY_UP,CommandType::NO_COMMAND},
    {KEY_PAGE_UP,CommandType::NO_COMMAND},
    {KEY_PAGE_DOWN,CommandType::NO_COMMAND},
    {KEY_HOME,CommandType::NO_COMMAND},
    {KEY_END,CommandType::NO_COMMAND},
    {KEY_CAPS_LOCK,CommandType::NO_COMMAND},
    {KEY_SCROLL_LOCK,CommandType::NO_COMMAND},
    {KEY_NUM_LOCK,CommandType::NO_COMMAND},
    {KEY_PRINT_SCREEN,CommandType::NO_COMMAND},
    {KEY_PAUSE,CommandType::NO_COMMAND},
    {KEY_F1,CommandType::NO_COMMAND},
    {KEY_F2,CommandType::NO_COMMAND},
    {KEY_F3,CommandType::NO_COMMAND},
    {KEY_F4,CommandType::NO_COMMAND},
    {KEY_F5,CommandType::NO_COMMAND},
    {KEY_F6,CommandType::NO_COMMAND},
    {KEY_F7,CommandType::NO_COMMAND},
    {KEY_F8,CommandType::NO_COMMAND},
    {KEY_F9,CommandType::NO_COMMAND},
    {KEY_F10,CommandType::NO_COMMAND},
    {KEY_F11,CommandType::NO_COMMAND},
    {KEY_F12,CommandType::NO_COMMAND},
    {KEY_LEFT_SHIFT,CommandType::NO_COMMAND},
    {KEY_LEFT_CONTROL,CommandType::NO_COMMAND},
    {KEY_LEFT_ALT,CommandType::NO_COMMAND},
    {KEY_LEFT_SUPER,CommandType::NO_COMMAND},
    {KEY_RIGHT_SHIFT,CommandType::NO_COMMAND},
    {KEY_RIGHT_CONTROL,CommandType::NO_COMMAND},
    {KEY_RIGHT_ALT,CommandType::NO_COMMAND},
    {KEY_RIGHT_SUPER,CommandType::NO_COMMAND},
    {KEY_KB_MENU,CommandType::NO_COMMAND},
    // Keypad keys
    {KEY_KP_0,CommandType::NO_COMMAND},
    {KEY_KP_1,CommandType::NO_COMMAND},
    {KEY_KP_2,CommandType::NO_COMMAND},
    {KEY_KP_3,CommandType::NO_COMMAND},
    {KEY_KP_4,CommandType::NO_COMMAND},
    {KEY_KP_5,CommandType::NO_COMMAND},
    {KEY_KP_6,CommandType::NO_COMMAND},
    {KEY_KP_7,CommandType::NO_COMMAND},
    {KEY_KP_8,CommandType::NO_COMMAND},
    {KEY_KP_9,CommandType::NO_COMMAND},
    {KEY_KP_DECIMAL,CommandType::NO_COMMAND},
    {KEY_KP_DIVIDE,CommandType::NO_COMMAND},
    {KEY_KP_MULTIPLY,CommandType::NO_COMMAND},
    {KEY_KP_SUBTRACT,CommandType::NO_COMMAND},
    {KEY_KP_ADD,CommandType::NO_COMMAND},
    {KEY_KP_ENTER,CommandType::NO_COMMAND},
    {KEY_KP_EQUAL,CommandType::NO_COMMAND},
    // Android key button
    {KEY_BACK,CommandType::NO_COMMAND},
    {KEY_MENU,CommandType::NO_COMMAND},
    {KEY_VOLUME_UP,CommandType::NO_COMMAND},
    {KEY_VOLUME_DOWN,CommandType::NO_COMMAND}
};


static std::map<MouseButton, CommandType> s_mouseButtonCommands = {
    {MOUSE_BUTTON_LEFT, CommandType::NO_COMMAND},
    {MOUSE_BUTTON_RIGHT, CommandType::NO_COMMAND},
    {MOUSE_BUTTON_MIDDLE, CommandType::NO_COMMAND},
    {MOUSE_BUTTON_SIDE, CommandType::NO_COMMAND},
    {MOUSE_BUTTON_EXTRA, CommandType::NO_COMMAND},
    {MOUSE_BUTTON_FORWARD, CommandType::NO_COMMAND},
    {MOUSE_BUTTON_BACK, CommandType::NO_COMMAND}
};


static std::map<GamepadButton, CommandType> s_gamepadButtonCommands = {
    {GAMEPAD_BUTTON_UNKNOWN, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_LEFT_FACE_UP, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_LEFT_FACE_RIGHT, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_LEFT_FACE_DOWN, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_LEFT_FACE_LEFT, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_RIGHT_FACE_UP, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_RIGHT_FACE_RIGHT, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_RIGHT_FACE_DOWN, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_RIGHT_FACE_LEFT, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_LEFT_TRIGGER_1, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_LEFT_TRIGGER_2, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_RIGHT_TRIGGER_1, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_RIGHT_TRIGGER_2, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_MIDDLE_LEFT, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_MIDDLE, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_MIDDLE_RIGHT, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_LEFT_THUMB, CommandType::NO_COMMAND},
    {GAMEPAD_BUTTON_RIGHT_THUMB, CommandType::NO_COMMAND}
};


static std::map<GamepadAxis, CommandType> s_gameAxisCommands = {
    {GAMEPAD_AXIS_LEFT_X, CommandType::NO_COMMAND},
    {GAMEPAD_AXIS_LEFT_Y, CommandType::NO_COMMAND},
    {GAMEPAD_AXIS_RIGHT_X, CommandType::NO_COMMAND},
    {GAMEPAD_AXIS_RIGHT_Y, CommandType::NO_COMMAND},
    {GAMEPAD_AXIS_LEFT_TRIGGER, CommandType::NO_COMMAND},
    {GAMEPAD_AXIS_RIGHT_TRIGGER,CommandType::NO_COMMAND}
};